### ISSUE TITLE
Оформление списков

### ISSUE THREAD

**Issue by illinc** [readysloth/Diploma#2]
Маркированный список:
— это;
— одно;
— длинное;
— предложение.
Нумерованный со скобками список:
а) тоже;
б) одно;
независимо от способа нумерации (к сожалению, гитлаб автоформатирует 1) и 2) в список с точками):
в) длинное;
г) предложение.

В нумерованном списке с точками.
1. Каждый элемент.
2. Является.
3. Отдельным предложением. Или абзацем.
4. Или даже.
Может состоять из нескольких абзацев.
5. А у вас все списки поперёк правил оформлены. И знаков препинания в конце элементов нигде нет.

**Comment by readysloth** [comment]
@illinc, а как поступать в таких случаях, когда список идет сразу после заголовка?
![image](https://user-images.githubusercontent.com/28711485/82117774-3984d680-977b-11ea-9f4c-a1ae54823a2f.png)
 1. Дописать введение, чтобы список стал частью предложения
 1. Оставить как есть
 1. Или сделать с ними что-то другое?...

**Comment by readysloth** [comment]
@illinc, я выложил новую версию отчета, с поправленными списками 
[pdf](https://github.com/readysloth/Diploma/releases/download/%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B8/dissertation.pdf)
[коммит](https://github.com/readysloth/Diploma/commit/46bd52ecfec2b75d8d6223ec2fda15a553d04dc3)

**Comment by illinc** [comment]
Введение в раздел нужно, даже если он не начинается со списка.
Так что первый вариант, конечно.
