### ISSUE TITLE
Нет введения в предметную область

### ISSUE THREAD

**Issue by illinc** [readysloth/Diploma#3]
Ни в диссертации, ни в слайдах нет:
— введения в предметную область;
— проблемной ситуации;
— постановки задачи.

**Comment by readysloth** [comment]
> Ни в диссертации, ни в слайдах нет:
> - проблемной ситуации;

Но у меня же есть в презентации табличка до/после...
![image](https://user-images.githubusercontent.com/28711485/82301417-e7cd8d80-99c0-11ea-9676-591a70ac312b.png)

Она совпадает с тем, как было в презентации, которую скинула Федотова как образцовую:
![image](https://user-images.githubusercontent.com/28711485/82301737-57dc1380-99c1-11ea-876a-12af73f3f131.png)

Но отличается от презентации Игоря Золотарева в отсутствии UML диаграммы...
Ее нужно добавить или что-то такое, похожее?
![image](https://user-images.githubusercontent.com/28711485/82301878-8823b200-99c1-11ea-907a-e189f1ba6603.png)

А в отчете (стр. 10, самый низ) у меня написано:
![image](https://user-images.githubusercontent.com/28711485/82302010-b73a2380-99c1-11ea-8294-36e31a21ef2e.png)

Я явно не писал, конечно, что это проблема, мне казалось это из текста понятно...
Потому что цель звучит так:
![image](https://user-images.githubusercontent.com/28711485/82302379-316aa800-99c2-11ea-9924-dc58aa9f6d27.png)

**Comment by readysloth** [comment]
> Ни в диссертации, ни в слайдах нет:
> - постановки задачи.

Разве постановка задачи это не первый слайд презентации?...
![image](https://user-images.githubusercontent.com/28711485/82302790-bf469300-99c2-11ea-9f05-a6c71bcab890.png)

Почти то же самое написано и в отчете (стр 16):
![image](https://user-images.githubusercontent.com/28711485/82303062-1ba9b280-99c3-11ea-8690-db87595ee827.png)
И в введении (стр 6-7)
![image](https://user-images.githubusercontent.com/28711485/82303123-33813680-99c3-11ea-973c-7dc7f3fe5a5c.png)
![image](https://user-images.githubusercontent.com/28711485/82303143-39771780-99c3-11ea-9ac3-c36ae524dd54.png)

**Comment by readysloth** [comment]
> Ни в диссертации, ни в слайдах нет:
> - введения в предметную область;

Но ведь я описываю предметную область внутри отчета в:
 - введении к отчету
 - в исследовательском разделе

Или я не так понимаю это...

**Comment by readysloth** [comment]
@illinc, прикрепил презентацию в репозиторий:
[pdf](https://github.com/readysloth/Diploma/releases/download/%D0%9F%D0%B5%D1%80%D0%B2%D0%B0%D1%8F_%D0%BF%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F/presentation.pdf)

**Comment by illinc** [comment]
1. По этой табличке непонятно ничего. Может быть, вы робота для поликлиники проектируете.

2. Вы серьёзно думаете, что то, что вам даётся — это образцовые документы?
Это документы, которые оказались у неё под рукой и хоть немного похожи структурой на то, что надо. Я сама была в ситуации, когда просят хоть какую-то рыбу, и в такой ситуации неизменно оказывается, что:
— архив с дисками со всеми дипломами недоступен, да и прочитать диск было бы не на чем;
— тот набор документов, что ты считаешь лучшим, автор, несмотря на просьбу, не прислал (или прислал туда и в таком виде, что сейчас не вытащишь);
— то, что прислали 5-10 лет назад, уже не соответствует новым правилам, традициям или даже номерам (а по опыту известно, что если скажешь «обязательно замените этот номер на ...», то никто не заменит);
вот и приходится выбирать из документов тех своих студентов, кто всё же прислал финальную, правленую версию, и за последние 2-5 лет.
Список вариантов для выбора в таком случае обычно содержит один элемент...

**Comment by illinc** [comment]
Постановка задачи *должна быть* на втором слайде презентации.
У вас её там нет.

**Comment by illinc** [comment]
«»

> > Ни в диссертации, ни в слайдах нет:
> > 
> > * введения в предметную область;
> 
> Но ведь я описываю предметную область внутри отчета в:
> 
>     * введении к отчету
> 
>     * в исследовательском разделе
> 
> 
> Или я не так понимаю это...

Где?
Сколько раз читала — не нашла...

**Comment by illinc** [comment]
>... отсутствии UML диаграммы...
> Ее нужно добавить или что-то такое, похожее?

Не обязательно именно UML, разные картинки бывают...
 
> А в отчете (стр. 10, самый низ) у меня написано:
> ![image](https://user-images.githubusercontent.com/28711485/82302010-b73a2380-99c1-11ea-8294-36e31a21ef2e.png)

А ваши таблицы загадочны, аки шумерские таблички, и комментариями так и не обросли.

> Я явно не писал, конечно, что это проблема, мне казалось это из текста понятно...
> Потому что цель звучит так:
> ![image](https://user-images.githubusercontent.com/28711485/82302379-316aa800-99c2-11ea-9924-dc58aa9f6d27.png)
А надо всё писать явно!!!
Потому что тут (и не только тут) реально непонятно, что конкретно вы имели в виду.
Ну проводят... Ну ищут... Что в этом плохого-то?

И не «это проблема, потому что цель звучит так», а цель формулируется потому, что проблема!

**Comment by readysloth** [comment]
> А ваши таблицы загадочны, аки шумерские таблички, и комментариями так и не обросли.
> И вообще, данные из вот этих таблиц 1 и 2 — они вам зачем нужны? (Это я не к тому, чтобы  убрать таблицы, а к тому, чтобы включить их в общую повествовательную канву... Которой у вас так и нет в первой главе!)

@illinc, я изменил введение. Подпись к двум табличкам маленькая, но, мне кажется, она описывает, зачем они нужны...
Вот она:
> После чего выносится решение о проведении анализа ПО на НДВ в процесс сертификации или его игнорирование, как некритичного.

Таблички и подписанный текст выстроены так:
Вот у нас схема для вынесения вердикта, по ней решаем, нужен ли анализ ПО или не нужен..
